filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/snort/snort_live.csv
  pipeline: "snort-csv-pipeline"
  from_beginning: true

  # Optional additional fields. These fields can be freely picked
  # to add additional information to the crawled log files for filtering
  #fields:
  #  level: debug
  #  review: 1
