rule AutoGenerated_Threat_Rule {
    meta:
        author = "CustomStyle_SOAR"
        date = "2026-10-03"
        description = "Auto-generated CustomStyle detection rule"
        framework = "Style_Change_Framework"

    strings:
        $str_0 = "cmd.exe /c" ascii wide nocase
        $str_1 = "eval(base64_decode" ascii wide nocase

    condition:
        any of ($str_*)
}
